### PR TITLE
Add options and bring to 100% code coverage.

### PR DESCRIPTION
**Pull request by sholladay**
Hi @vadimdemedes, great project!

These changes will enable me to use `google-images` in an app where image search is a core feature and thus I need users to be able to control the search criteria a bit more.

The tests are just copy/paste + the obvious tweaks for the relevant query parameter.

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Thank you, @sholladay!

I like this PR, great stuff!

Could you add a few examples to the "Usage" code in the readme?

**Comment by sholladay** [comment]
Okay, instead of that, I went and added full API documentation for everything. Should be clear and obvious now.

Also tested a few more edge cases, bringing coverage up to 100%.

**Comment by sholladay** [comment]
Updated the PR with full API documentation for everything. How's that @vadimdemedes?

Also tested a few more edge cases, bringing coverage up to 100%.

Doubled the total line count in the repo. 😎

**Comment by vadimdemedes** [comment]
Superb work, @sholladay! Thank you and sorry for such a late response!

**Pull request merged**
